#!/bin/sh
# Generated by vim-plug
# mar. 15 déc. 2015 15:02:33 CET

vim -c 'let g:plug_shallow = 0 | PlugUpdate | qa'

PLUG_HOME=~/.vim/bundle

cd $PLUG_HOME/Colorizer/ && git reset --hard 3ac2e7f
cd $PLUG_HOME/YouCompleteMe/ && git reset --hard 93c2a86
cd $PLUG_HOME/delimitMate/ && git reset --hard 8bc47fd
cd $PLUG_HOME/gundo.vim/ && git reset --hard dd5ab1e
cd $PLUG_HOME/lldb.nvim/ && git reset --hard c707279
cd $PLUG_HOME/mru.vim/ && git reset --hard 9f25db6
cd $PLUG_HOME/nerdcommenter/ && git reset --hard 1f4bfd5
cd $PLUG_HOME/nerdtree/ && git reset --hard 4ebbb53
cd $PLUG_HOME/rust.vim/ && git reset --hard 2450ecf
cd $PLUG_HOME/syntastic/ && git reset --hard 48736aa
cd $PLUG_HOME/tagbar/ && git reset --hard 7b36c46
cd $PLUG_HOME/ultisnips/ && git reset --hard 5a2dcc5
cd $PLUG_HOME/vim-airline/ && git reset --hard 14d14cf
cd $PLUG_HOME/vim-cargo/ && git reset --hard 6d3e8d7
cd $PLUG_HOME/vim-fugitive/ && git reset --hard 207c643
cd $PLUG_HOME/vim-json/ && git reset --hard f5e3181
cd $PLUG_HOME/vim-man/ && git reset --hard 3d26cb1
cd $PLUG_HOME/vim-markdown-composer/ && git reset --hard 67257d5

